# 04 Data Preprocessing dengan Scikit-Learn

## Sample Data

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array ([[2.1, -1.9, 5.5],
                         [-1.5, 2.4, 3.5],
                         [0.5, -7.9, 5.6],
                         [5.9, 2.3, -5.8]])
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [3]:
sample_data.shape

(4, 3)

## Binarisation

In [4]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [5]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
pinarised_data = preprocessor.transform(sample_data)
pinarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])